/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nicova.hotel;

import com.nicova.controllers.GetClientes;
import com.nicova.controllers.GetUsers;
import static com.nicova.hotel.DashBoard.verificarYCrearArchivoCSV;
import com.nicova.objetos.Cliente;
import com.nicova.objetos.Usuario;
import java.security.GeneralSecurityException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class Login extends javax.swing.JFrame {
    

    String csvFile = "C:\\Nicova\\usuarios.csv";

    List<Usuario> listaUsuario = GetUsers.leerUsuarios(csvFile);
    
    public Login() throws GeneralSecurityException {
        com.nicova.hotel.DashBoard.verificarYCrearArchivoCSV("C:\\Nicova\\usuarios.csv", "1eryWNc7sn1KG8PlZFsfsin-DH6NP5SQAgWCUDTk17ys");
        initComponents();
        InitStyles();
        this.setLocationRelativeTo(bg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        usuarioSeparator = new javax.swing.JSeparator();
        pass = new javax.swing.JLabel();
        passSeparator = new javax.swing.JSeparator();
        loginBtn = new javax.swing.JPanel();
        loginBtnTxt = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        bg.setBackground(new java.awt.Color(38, 50, 56));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nicova/imagenes/LOGO NICOVA DORADO 321x250.png"))); // NOI18N
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 321, 250));

        iniciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 26)); // NOI18N
        iniciarSesion.setForeground(new java.awt.Color(200, 172, 84));
        iniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciarSesion.setText("INICIAR SESIÓN");
        bg.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 340, -1));

        usuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(200, 172, 84));
        usuario.setText("USUARIO");
        bg.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 300, 20));

        usuarioSeparator.setBackground(new java.awt.Color(200, 172, 84));
        usuarioSeparator.setForeground(new java.awt.Color(200, 172, 84));
        bg.add(usuarioSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 330, -1));

        pass.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(200, 172, 84));
        pass.setText("CONTRASEÑA");
        bg.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 160, 20));

        passSeparator.setBackground(new java.awt.Color(200, 172, 84));
        passSeparator.setForeground(new java.awt.Color(200, 172, 84));
        bg.add(passSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 330, -1));

        loginBtn.setBackground(new java.awt.Color(200, 172, 84));

        loginBtnTxt.setBackground(new java.awt.Color(200, 172, 84));
        loginBtnTxt.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        loginBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtnTxt.setText("INGRESAR");
        loginBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 210, 50));

        usuarioTxt.setBackground(new java.awt.Color(38, 50, 56));
        usuarioTxt.setForeground(new java.awt.Color(153, 153, 153));
        usuarioTxt.setBorder(null);
        bg.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 330, 30));

        passTxt.setBackground(new java.awt.Color(38, 50, 56));
        passTxt.setForeground(new java.awt.Color(153, 153, 153));
        passTxt.setBorder(null);
        bg.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 330, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void InitStyles() {
        usuarioTxt.putClientProperty("JTextField.placeholderText", "Ingrese El Nombre De Usuario.");
    }

    private void loginBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxtMouseClicked
        DashBoard ventana;
        boolean check = false;
        for (Usuario user : listaUsuario) {
            if (user.getDocumento().equals(usuarioTxt.getText()) && user.getcontraseña().equals(passTxt.getText())) {
                check = true;
                try {

                    ventana = new DashBoard();

                    ventana.setExtendedState(JFrame.MAXIMIZED_BOTH);

                    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                    int screenWidth = screenSize.width;
                    int screenHeight = screenSize.height;

                    ventana.setLocation(0, 0);
                    ventana.setUser(user);
                    

                    ventana.setVisible(true);
                    dispose();
                } catch (GeneralSecurityException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (check == false) {
            JOptionPane.showMessageDialog(null, "El usuario y/o contraseña es incorrecta", "Error", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_loginBtnTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (GeneralSecurityException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JLabel loginBtnTxt;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pass;
    private javax.swing.JSeparator passSeparator;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel usuario;
    private javax.swing.JSeparator usuarioSeparator;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
